export const GET_TESTS_START = "GET_TESTS_START";
export const GET_TESTS_SUCCESS = "GET_TESTS_SUCCESS";
export const GET_TESTS_FAILURE = "GET_TESTS_FAILURE";

export const GET_ONE_TEST_START = "GET_ONE_TEST_START";
export const GET_ONE_TEST_SUCCESS = "GET_ONE_TEST_SUCCESS";
export const GET_ONE_TEST_FAILURE = "GET_ONE_TEST_FAILURE";

export const CLEAN_UP = "CLEAN_UP";
